### ISSUE TITLE
curious to know

### ISSUE THREAD

**Issue by manwar** [ThisUsedToBeAnEmail/MooX-ValidateSubs#1]
Hi,

Just curious to know why the following line having 4 shift in the method _validate_sub()

my ($self, $name, $type, $stored_spec) = (shift, shift, shift, shift);

instead of 

my ($self, $name, $type, $stored_spec) = @_;

Best Regards,
Mohammad S Anwar

**Comment by ThisUsedToBeAnEmail** [comment]
Hey,

Probably because when I started I wrote the following two lines of code, 

my ($name, $spec) = (shift, shift); 
my @params = @_ ;

Which I personally think is much nicer than...

my ($name, $spec) = @_ ;
my @params = @_ ;

I have nothing against @_ but I tend to use it when I want *everything* and not when I want one/two vars I could just shift. Maybe 4 is too many is their any advantage to switching to @_, If I was to change that line I might do something like....

my ( $self, $name, $type, $spec, @params ) = @_;

Kind Regards

Robert.

**Comment by manwar** [comment]
Hi,

I take your points.
I would personally prefer the following line:

my ( $self, $name, $type, $spec, @params ) = @_;

Nice and clean.

BTW,

my ($name, $spec) = (shift, shift);
my @params = @_ ;

is not the same as below

my ($name, $spec) = @_ ;
my @params = @_ ;

Keep up the good work :-)

Best Regards,
Mohammad S Anwar

**Comment by ThisUsedToBeAnEmail** [comment]
Nope you are right, they are not, shift removes the first value from @_. so in my example @params would contain name and spec which is bad ... see their was a reason why :)

**Comment by manwar** [comment]
It is now safe to close the issue :-)
